name: architect
description: A simple command-line application to analyze Dart/Flutter app's architecture.
version: 0.1.0
homepage: https://github.com/Antriadus/architect
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^2.0.0
  meta: ^1.3.0
  yaml: ^3.1.0
  args: ^2.0.0
  path: ^1.8.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0

